### ISSUE TITLE
Dnstwist updates

### ISSUE THREAD

**Issue by advancedeng** [0xd34db33f/gfyp#1]
Hi, I was wondering whether your scripts keep updated while dnstwist get more capabilities in terms of typosquatting detection.

**Comment by 0xd34db33f** [comment]
Yep there will be updates to the dnstwist library in GFYP here soon. Just need to find some time to work on it due to $dayjob commitments at the moment.

**Comment by advancedeng** [comment]
Thanks a lot for the update, much appreciated!

**Comment by 0xd34db33f** [comment]
Codebase has been updated with most recent copy of dnstwist library. For the next version, I'm planning on moving it over to a modular plug-in style architecture here so you can add additional library fuzzy as you wish so hopefully it'll be more open for additional libraries.

**Comment by advancedeng** [comment]
Great stuff !! Just le us know when the next version will be ready!

Cheers,
Andreas
