### ISSUE TITLE
Implementing logging

### ISSUE THREAD

**Issue by kristovatlas** [0xd34db33f/gfyp#5]
The application should log stuff, either in a system log or an application-specific one for debugging.

**Comment by 0xd34db33f** [comment]
Again another good idea. Syslog does seem like the more convenient fix, however I have heard from some folks who say they use it under Windows as well. Not sure what the current state of Windows Event log writing is under Python, but all things being equal I'd say just some application-specific one using logging would probably be the most universal option.

**Comment by kristovatlas** [comment]
This was satisfied by https://github.com/0xd34db33f/gfyp/pull/8
